version: "3.3"
services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - 3001:80
    volumes:
      - ./app:/usr/src/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    container_name: php
    build: ./docker/php
    working_dir: /usr/src/api
    volumes:
      - ./api:/usr/src/api
    ports:
      - 9000:9000