version: "3.3"
volumes:
  db-data:
services:
  nginx_front:
    container_name: nginx-front
    image: nginx:stable-alpine
    ports:
      - 3001:80
    volumes:
      - ./app:/usr/src/app
      - ./docker/nginx/default-front.conf:/etc/nginx/conf.d/default.conf
  nginx_api:
    container_name: nginx-api
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - ./api:/usr/src/api
      - ./docker/nginx/default-api.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    container_name: php
    build: ./docker/php
    working_dir: /usr/src/api
    volumes:
      - ./api:/usr/src/api
    ports:
      - 9000:9000
  database:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: api
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: database
    ports:
      - 8080:8080
