<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB7eVoxo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB7eVoxo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB7eVoxo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB7eVoxo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB7eVoxo\App_KernelDevDebugContainer([
    'container.build_hash' => 'B7eVoxo',
    'container.build_id' => '1e68f954',
    'container.build_time' => 1649248682,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB7eVoxo');
